Update python-tests.yml

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -15,8 +15,10 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+
       - name: Install gcc
         run: sudo apt-get install gcc
+
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
@@ -38,33 +40,28 @@ jobs:
           sudo apt-get install -y openjdk-17-jdk
           java -version
 
-      - name: Run tests
+      - name: Run tests with coverage
         run: |
           coverage run --source=game -m unittest discover
           coverage report
-          coverage xml -o coverage.xml
-          #lcov --capture --directory . --output-file lcov.info
-
-      - name: Run tests with coverage
-        run: |
-          coverage run -m unittest discover
-          coverage report
           coverage html
           coverage xml -o coverage.xml
+          lcov --capture --directory . --output-file lcov.info || echo "lcov generation failed"
 
       - name: Upload coverage report
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v3  # Обновленная версия
         with:
           name: coverage-report
           path: coverage.xml
 
-      #- name: Check for lcov.info
-      #  run: |
-      #    if [ -f lcov.info ]; then
-      #      echo "lcov.info exists."
-      #    else
-      #      echo "lcov.info does not exist."
-      #      exit 1
+      - name: Check for lcov.info
+        run: |
+          if [ -f lcov.info ]; then
+            echo "lcov.info exists."
+          else
+            echo "lcov.info does not exist."
+            exit 1
+          fi
 
       - name: Run SonarCloud analysis
         uses: sonarsource/sonarcloud-github-action@master
